"""empty message

Revision ID: 524bb96cd496
Revises: bb12eb0167ab
Create Date: 2020-12-21 12:16:48.791511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524bb96cd496'
down_revision = 'bb12eb0167ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
