"""empty message

Revision ID: 636216781eac
Revises: 524bb96cd496
Create Date: 2020-12-21 12:36:36.937634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636216781eac'
down_revision = '524bb96cd496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
